### ISSUE TITLE
Correct LogBook (too much white)

### ISSUE THREAD

**Issue by jpromerob** [jpromerob/HL2019_Project#127]
There is now a function (resizeSubplot) allowing automatically resize the subplotted figures and prevent what is shown here:
![image](https://user-images.githubusercontent.com/34107797/36928665-f96f53a4-1e87-11e8-8c2d-58a38f06e64d.png)
That function should be used before saving subplotted figures.
This issue is linked to Issue #126

**Comment by jpromerob** [comment]
@adelphin , the following Figures need to be either re-factored or re-generated somehow because they have wide white margins that make the render too ugly:
HRChest32, HRChest128, HRSheppLogan32, HRDiff, HRNoise, HRMoved

**Comment by adelphin** [comment]
Those images correspond to 4Images, HRSheppLogan32 and HRChest32

**Comment by jpromerob** [comment]
I think that the problem you talk about (image distortion) can be relatd to this
https://github.com/jpromerob/HL2019_Project/issues/118
**When working with pixelated images, it is better to use *.png instead of *.eps. Tex seems to try to 'improve' eps and we don't want that **
