### ISSUE TITLE
Write Final Presentation

### ISSUE THREAD

**Issue by cescob** [jpromerob/HL2019_Project#155]
The project is almost at the end....and I have never opened an issue!!!
So this is the good chance to do it.
I shared a drive link with the shell of the Presentation based on the half time presentation

**Comment by jpromerob** [comment]
Here it is:
https://github.com/jpromerob/HL2019_Project/blob/master/Slides/HL2019_Final_Presentation_BASSO_DELPHIN_ROMERO.pdf
