### ISSUE TITLE
Play with NiftyRec

### ISSUE THREAD

**Issue by jpromerob** [jpromerob/HL2019_Project#55]
I'm stuck here:
![image](https://user-images.githubusercontent.com/34107797/35892049-c99f938e-0ba7-11e8-8089-879a377889fa.png)

**Comment by adelphin** [comment]
After 10 or more tries to build Niftyrec I always get the same error on matlab.

> et_demo_mlem
> Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more
> information, click here. 
> Creating synthetic sinogram..
> Undefined function or variable 'et_project_mex'.
> 
> Error in et_project (line 91)
> sinogram = et_project_mex(activity, cameras, attenuation, psf, use_gpu, background, background_attenuation,
> truncate_negative_values);
> 
> Error in et_demo_mlem (line 54)
> ideal_sinogram = et_project(phantom, cameras, attenuation, psf, GPU);

I declare the end of our interest in this!
