### ISSUE TITLE
Play with MIRT

### ISSUE THREAD

**Issue by jpromerob** [jpromerob/HL2019_Project#59]
More info can be found [here](https://web.eecs.umich.edu/~fessler/code/)

**Comment by adelphin** [comment]
Francesco and I just tried to run some IMRT code
Looooots of errors that we don't understood, sometimes it seems the problem is that the code was written for matlab 2006 or 2007 and is now broken

**Comment by jpromerob** [comment]
Good to know!
Don't forget to update the logbook with this information as we did for Occiput and NiftyRec (copy/paste-ing error logs or adding screenshots).
Moreover, if you considered that we can close this issue, just do it.
