### ISSUE TITLE
Implement Super-Resolution Algorithm for Synthetic Images

### ISSUE THREAD

**Issue by jpromerob** [jpromerob/HL2019_Project#96]
Depends on Issue #95

**Comment by adelphin** [comment]
HRAlgo.m does a nice reconstruction with noise free images.
Should be tested with noise, and with inequal geometric transformations between the 4 input acquisitions

**Comment by jpromerob** [comment]
@adelphin : will you be working on something for this issue or is it possible to close it now?

**Comment by adelphin** [comment]
I think we're done with that, I'll close.
