### ISSUE TITLE
Implement PSF correction

### ISSUE THREAD

**Issue by jpromerob** [jpromerob/HL2019_Project#97]
So far, the sinograms are generated by taking into account a discrete distribution of rays. 
A correction must be done so as to account for contributions done by rays in the neighborhood of a given collimator hole. For this, information regarding Point Spread Function (from Lab2) must be used. Not that PSF is 'modulated' by increasing/decreasing the distance between the source and the detector.

**Comment by cescob** [comment]
I think we can close this:)

**Comment by jpromerob** [comment]
Not enough time to do this.
